# Generated by Django 5.0.3 on 2024-03-27 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("roadmap", "0001_initial"),
        ("roadmap", "0002_alter_vertex_depends"),
        ("roadmap", "0003_alter_vertex_depends"),
        ("roadmap", "0004_alter_vertex_depends"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EntryLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LocalDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MetaDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255, unique=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="r_tags",
                        related_query_name="r_tag",
                        to="roadmap.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfoCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("links", models.TextField(blank=True)),
                (
                    "entry_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="roadmap.entrylevel",
                    ),
                ),
                (
                    "knowledge_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="roadmap.knowledgetype",
                    ),
                ),
                (
                    "local_domain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="roadmap.localdomain",
                    ),
                ),
                (
                    "meta_domain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="roadmap.metadomain",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="ic_tags",
                        related_query_name="ic_tag",
                        to="roadmap.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vertex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depends", models.ManyToManyField(blank=True, to="roadmap.vertex")),
                (
                    "info_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmap.infocard",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmap.roadmap",
                    ),
                ),
            ],
        ),
    ]
