services:
  db-test:
    container_name: db-test
    image: postgres:12.0-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      PGDATAPGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3

  web-test:
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - db-test
    depends_on:
      db-test:
        condition: service_healthy
    env_file:
      - .env
    environment:
      ALLOWED_HOSTS: "*"
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      DB_HOST: db-test
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: career_skill_atlas.config.test_settings
    command: [ "python", "-Wd", "manage.py", "test", "--settings=career_skill_atlas.config.test_settings"]
